<a href="https://colab.research.google.com/github/RanggaSanjayaSakti/Data_Mining_project_2/blob/main/RedWineQuality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Understanding

## Business Understanding

### Business objective
jadi tujuan bisnis dari dataset ini adalah untuk menganalisis dataset yang dapat membantu produsen red wine untuk memahami faktor-faktor apa saja yang berkontribusi terhadap kualitas red wine sehingga dapat membuat perubahan yang di perlukan untuk meningkatkan kualitas produk.

### Assess situation
Situasi bisnis yang mendasari analisis ini adalah banyaknya para kompetitor yang bersaing dalam meningkatkan pasar dan dalam meningkatkan kualitas yang lebih baik untuk menarik minat konsumen.

### Tujuan data mining
Tujuan data mining dari dataset red wine quality adalah untuk mengeksplorasi dan mengekstrak pola atau informasi berharga yang tersembunyi dalam data tersebut, dan juga untuk mengoptimasi produksi yaitu menggunakan data untuk mengoptimalkan parameter produksi guna meningkatkan kualitas dan mengurangi variasi dalam hasil red wine, lalu untuk mengidentifikasi tren pasar yaitu untuk menjelajahi data untuk mengidentifikasi tren pasar dan preferensi konsumen yang dapat memberikan keunggulan kompetitif.

### Rencana proyek
Jadi tahapan tahapan yang dilakukan adalah

1. melakukan analisis eksploratif data yaitu melakukan EDA pada dataset red wine quality untuk memahami distribusi fitur, korelasi antar variabel, dll.
2. identifikasi faktor kualitas utama yaitu menggunakan teknik data mining untuk menentukan faktor-faktor kunci yang memengaruhi kualitas red wine.
3. segmentasi pasar yaitu mengidentifikasi segmen pasar yang memiliki preferensi kualitas tertentu.
4. optimasi produk yaitu menggunakan hasil analisis data untuk mengoptimalkan parameter-produksi guna mencapai konsistensi kualitas dan mengurangi variasi hasil anggur.
5. Strategi Pemasaran: Berdasarkan hasil analisis data, susun strategi pemasaran yang dapat menonjolkan keunggulan produk dan menarik segmen pasar yang diidentifikasi.



# Data Understanding

## Collect Initial Data

Dataset ini berasal dari website kaggle dan dataset ini terfokus pada varian anggur merah"vinho verde"portugal.lalu dataset ini hanya menyertakan variabel fisikokimia (input) dan sensori (output).untuk referensi dari dataset ini bisa ditemukan dengan merujuk kepenelitian asli yaitu(cortez et al.,2009).
https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009

In [16]:
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("winequality-red.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

# Describe Data

## informasi dasar

In [7]:
jumlah_baris, jumlah_kolom = df.shape
print(f"Jumlah Baris: {jumlah_baris}")
print(f"Jumlah Kolom: {jumlah_kolom}")

Jumlah Baris: 1599
Jumlah Kolom: 12


Dan untuk informasi baris dan kolom dari dataset ini adalah untuk barisnya yaitu berjumlah 1599 dan jumlah kolomnya yaitu 12

## informasi lanjutan

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


untuk informasi lengkap dari dataset ini adalah
1. nama kolom : fixed acidity
   jumlah : 1599
   tipe data : float64
2. nama kolom : volatile acidity
   jumlah : 1599
   tipe data : float64
3. nama kolom : citric acid
   jumlah : 1599
   tipe data : float64
4. nama kolom : residual sugar
   jumlah : 1599
   tipe data : float64
5. nama kolom : chlorides
   jumlah : 1599
   tipe data : float64
6. nama kolom : free sulfur dioxide
   jumlah : 1599
   tipe data : float64
7. nama kolom : total sulfur dioxide
   jumlah : 1599
   tipe data : float64
8. nama kolom : density
   jumlah : 1599
   tipe data : float64
9. nama kolom : pH
   jumlah : 1599
   tipe data : float64
10. nama kolom : sulphates
   jumlah : 1599
   tipe data : float64
11. nama kolom : alcohol
   jumlah : 1599
   tipe data : float64
12. nama kolom : quality
   jumlah : 1599
   tipe data : int64

## informasi statistik deskriptif

In [9]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

Berikut adalah data statistik deskriptif untuk setiap kolom pada dataset red wine quality:

Fixed Acidity :
- Jumlah: 1599
- Rata-rata: 8.319637
- Standar Deviasi: 1.741096
- Minimum: 4.6
- 25%: 7.1
- 50%: 7.9
- 75%: 9.2
- Maksimum: 15.9

Volatile Acidity :
- Jumlah: 1599
- Rata-rata: 0.527821
- Standar Deviasi: 0.179060
- Minimum: 0.12
- 25%: 0.39
- 50%: 0.52
- 75%: 0.64
- Maksimum: 1.58

Citric Acid :
- Jumlah: 1599
- Rata-rata: 0.270976
- Standar Deviasi: 0.194801
- Minimum: 0.0
- 25%: 0.09
- 50%: 0.26
- 75%: 0.42
- Maksimum: 1.0

Residual Sugar :
- Jumlah: 1599
- Rata-rata: 2.538806
- Standar Deviasi: 1.409928
- Minimum: 0.9
- 25%: 1.9
- 50%: 2.2
- 75%: 2.6
- Maksimum: 15.5

Chlorides:
- Jumlah: 1599
- Rata-rata: 0.087467
- Standar Deviasi: 0.047065
- Minimum: 0.012
- 25%: 0.07
- 50%: 0.079
- 75%: 0.09
- Maksimum: 0.611

Free Sulfur Dioxide :
- Jumlah: 1599
- Rata-rata: 15.874922
- Standar Deviasi: 10.460157
- Minimum: 1.0
- 25%: 7.0
- 50%: 14.0
- 75%: 21.0
- Maksimum: 72.0

Total Sulfur Dioxide :
- Jumlah: 1599
- Rata-rata: 46.467792
- Standar Deviasi: 32.895324
- Minimum: 6.0
- 25%: 22.0
- 50%: 38.0
- 75%: 62.0
- Maksimum: 289.0

Density :
- Jumlah: 1599
- Rata-rata: 0.996747
- Standar Deviasi: 0.001887
- Minimum: 0.99007
- 25%: 0.9956
- 50%: 0.99675
- 75%: 0.997835
- Maksimum: 1.00369

pH:
- Jumlah: 1599
- Rata-rata: 3.311113
- Standar Deviasi: 0.154386
- Minimum: 2.74
- 25%: 3.21
- 50%: 3.31
- 75%: 3.4
- Maksimum: 4.01

Sulphates :
- Jumlah: 1599
- Rata-rata: 0.658149
- Standar Deviasi: 0.169507
- Minimum: 0.33
- 25%: 0.55
- 50%: 0.62
- 75%: 0.73
- Maksimum: 2.0

Alcohol :
- Jumlah: 1599
- Rata-rata: 10.422983
- Standar Deviasi: 1.065668
- Minimum: 8.4
- 25%: 9.5
- 50%: 10.2
- 75%: 11.1
- Maksimum: 14.9

Quality :
- Jumlah: 1599
- Rata-rata: 5.636023
- Standar Deviasi: 0.807569
- Minimum: 3.0
- 25%: 5.0
- 50%: 6.0
- 75%: 6.0
- Maksimum: 8.0

# Exploratory Data Analysis

In [10]:
plt.figure(figsize=(8, 6))
sns.countplot(x='quality', data=df  , palette='viridis')
plt.title('Distribusi Kualitas Anggur')
plt.xlabel('Kualitas')
plt.ylabel('Jumlah')
plt.show()

<ipython-input-10-fd3cf7b77f16>:2: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.countplot(x='quality', data=df  , palette='viridis')


visualisasi diatas menunjukkan distribusi jumlah observasi untuk setiap tingkat kualitas anggur yang ada didalam dataset ini dan dapat dilihat bahwa kualitas anggur banyak yang berada pada nilai 5 dan 6, dapat diasumsi kan bahwa sebagian besar anggur dalam dataset ini memiliki kualitas yang cukup baik, dan sementara untuk kulaitas yang lebih rendah sangat jarang ditemui.

# Verify Data Quality

## Missing Values

In [11]:
missing_values = df.isnull().sum()

print(missing_values)

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64


Hasil yang ditampilkan menunjukkan bahwa tidak ada nilai kosong (missing values) dalam dataset untuk setiap kolom. Setiap kolom memiliki jumlah nilai kosong yang sama dengan 0. Dengan kata lain, dataset ini lengkap, dan tidak ditemukan nilai yang hilang dalam kolom-kolom yang disebutkan.

## Outliers Values

In [12]:
def detect_outliers(column):
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3 - Q1

    outliers = (column < (Q1 - 1.5 * IQR)) | (column > (Q3 + 1.5 * IQR))

    percentage_outliers = outliers.sum() / len(column) * 100

    return outliers, percentage_outliers

for column in df.columns:
    outliers, percentage_outliers = detect_outliers(df[column])

    print(f"Kolom '{column}':")
    print(f"  - Jumlah outliers: {outliers.sum()}")
    print(f"  - Persentase kehadiran outliers: {percentage_outliers:.2f}%")
    print()


Kolom 'fixed acidity':
  - Jumlah outliers: 49
  - Persentase kehadiran outliers: 3.06%

Kolom 'volatile acidity':
  - Jumlah outliers: 19
  - Persentase kehadiran outliers: 1.19%

Kolom 'citric acid':
  - Jumlah outliers: 1
  - Persentase kehadiran outliers: 0.06%

Kolom 'residual sugar':
  - Jumlah outliers: 155
  - Persentase kehadiran outliers: 9.69%

Kolom 'chlorides':
  - Jumlah outliers: 112
  - Persentase kehadiran outliers: 7.00%

Kolom 'free sulfur dioxide':
  - Jumlah outliers: 30
  - Persentase kehadiran outliers: 1.88%

Kolom 'total sulfur dioxide':
  - Jumlah outliers: 55
  - Persentase kehadiran outliers: 3.44%

Kolom 'density':
  - Jumlah outliers: 45
  - Persentase kehadiran outliers: 2.81%

Kolom 'pH':
  - Jumlah outliers: 35
  - Persentase kehadiran outliers: 2.19%

Kolom 'sulphates':
  - Jumlah outliers: 59
  - Persentase kehadiran outliers: 3.69%

Kolom 'alcohol':
  - Jumlah outliers: 13
  - Persentase kehadiran outliers: 0.81%

Kolom 'quality':
  - Jumlah outliers

1. Kolom 'fixed acidity':
- Jumlah outliers: 49
- Persentase kehadiran outliers: 3.06%
- Terdapat 49 nilai yang dianggap sebagai outliers dalam kolom 'fixed - acidity'. Persentase ini mencerminkan seberapa besar persentase data yang dianggap sebagai nilai yang ekstrem.

2.Kolom 'volatile acidity':
- Jumlah outliers: 19
- Persentase kehadiran outliers: 1.19%
- Ditemukan 19 nilai yang dianggap sebagai outliers dalam kolom 'volatile acidity'. Persentase kehadiran outliers relatif rendah.

3. Kolom 'citric acid':
- Jumlah outliers: 1
- Persentase kehadiran outliers: 0.06%
- Hanya ada 1 nilai yang dianggap sebagai outlier dalam kolom 'citric acid'. Persentase kehadiran outliers sangat rendah.

4. Kolom 'residual sugar':
- Jumlah outliers: 155
- Persentase kehadiran outliers: 9.69%
- Terdapat 155 nilai yang dianggap sebagai outliers dalam kolom 'residual sugar'. Persentase kehadiran outliers tinggi.

5. Kolom 'chlorides':
- Jumlah outliers: 112
- Persentase kehadiran outliers: 7.00%
- Ditemukan 112 nilai yang dianggap sebagai outliers dalam kolom 'chlorides'. Persentase kehadiran outliers cukup signifikan.

## Duplicated Values

In [14]:
duplicate_values =(df.duplicated())

print("Apakah Ada Nilai Duplikat pada Tiap Kolom:")
print(duplicate_values)

Apakah Ada Nilai Duplikat pada Tiap Kolom:
0       False
1       False
2       False
3       False
4        True
        ...  
1594    False
1595    False
1596     True
1597    False
1598    False
Length: 1599, dtype: bool


untuk hasil dari duplikat dataset yang ada di atas dapat disimpulkan bahwa banyak data yang tidak duplikat sehingga tidak berpengaruh terhadap statistik deskriptif yang berarti bisa menjadi bias dan tidak mencerminkan variasi sebenarnya didalam dataset.

In [19]:
(df[df.duplicated()])

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
4               7.4             0.700         0.00            1.90      0.076   
11              7.5             0.500         0.36            6.10      0.071   
27              7.9             0.430         0.21            1.60      0.106   
40              7.3             0.450         0.36            5.90      0.074   
65              7.2             0.725         0.05            4.65      0.086   
...             ...               ...          ...             ...        ...   
1563            7.2             0.695         0.13            2.00      0.076   
1564            7.2             0.695         0.13            2.00      0.076   
1567            7.2             0.695         0.13            2.00      0.076   
1581            6.2             0.560         0.09            1.70      0.053   
1596            6.3             0.510         0.13            2.30      0.076   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
4                    11.0                  34.0  0.99780  3.51       0.56   
11                   17.0                 102.0  0.99780  3.35       0.80   
27                   10.0                  37.0  0.99660  3.17       0.91   
40                   12.0                  87.0  0.99780  3.33       0.83   
65                    4.0                  11.0  0.99620  3.41       0.39   
...                   ...                   ...      ...   ...        ...   
1563                 12.0                  20.0  0.99546  3.29       0.54   
1564                 12.0                  20.0  0.99546  3.29       0.54   
1567                 12.0                  20.0  0.99546  3.29       0.54   
1581                 24.0                  32.0  0.99402  3.54       0.60   
1596                 29.0                  40.0  0.99574  3.42       0.75   

      alcohol  quality  
4         9.4        5  
11       10.5        5  
27        9.5        5  
40       10.5        5  
65       10.9        5  
...       ...      ...  
1563     10.1        5  
1564     10.1        5  
1567     10.1        5  
1581     11.3        5  
1596     11.0        6  

[240 rows x 12 columns]